// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "github.com/jinzhu/gorm"

type NewUser struct {
	Name string `json:"name",gorm:"unique"`
}

type User struct {
	gorm.Model
	Name string `json:"name"`
}
